name: Build Kernel
description: 'Builds the skyline kernel'

inputs:
  arch:
    description: 'Primary Architecture'
    required: true
    default: 'x86_64'
  subarch:
    description: 'Subarchitecture'
    required: true
    default: ''
  bootloader:
    description: 'The bootloader'
    required: true
    default: 'uefi'
  registry_password:
    description: 'GHCR token'
    required: true

runs:
  using: 'ubuntu-latest'
  steps:
  - name: Login to GHCR
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.registry_token }}
  - name: 'Build kernel'
    uses: 'docker://ghcr.io/skyline-operating-system/kernel-buildbot:latest'
    env:
      SKYLINE_ARCH: ${{ inputs.arch }}
      SKYLINE_SUB_ARCH: ${{ inputs.subarch }}
      SKYLINE_BOOTLOADER: ${{ inputs.bootloader }}
