name: Build Kernel(s)

on:
  push:

jobs:
  x86_64-uefi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build kernel
        uses: ./.github/actions/build-kernel
        with:
          arch: x86_64
          subarch:
          bootloader: uefi
          registry_password: ${{ secrets.GITHUB_TOKEN }}
